package com.csye6225.fall.Student_Info_System.datamodel;

import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
@DynamoDBTable(tableName="Lecture")
public class Lecture {
	private String Id;
	private String lec_Name;
	private String lec_Id;
	private List<String> nodes;
	private List<String> materials;
	private String lec_course_id;//assume one lecture only relate to one course
	
	public Lecture() {
		this.nodes=new ArrayList<>();
		this.materials=new ArrayList<>();
	}
	

	public Lecture(String lec_Name, String lec_Id, List<String> nodes, List<String> materials, String lec_course_id) {
		super();
		this.lec_Name = lec_Name;
		this.lec_Id = lec_Id;
		this.nodes = nodes;
		this.materials = materials;
		this.lec_course_id = lec_course_id;
	}

	
	@DynamoDBHashKey(attributeName="Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return Id;
	}


	public void setId(String id) {
		Id = id;
	}


	@DynamoDBAttribute(attributeName="LectureName")
	public String getLec_Name() {
		return lec_Name;
	}

	public void setLec_Name(String lec_Name) {
		this.lec_Name = lec_Name;
	}

	@DynamoDBIndexHashKey(attributeName="LectureId",globalSecondaryIndexName="Lecture_LectureId")
	public String getLec_Id() {
		return lec_Id;
	}

	public void setLec_Id(String lec_Id) {
		this.lec_Id = lec_Id;
	}

	@DynamoDBAttribute(attributeName="Nodes")
	public List<String> getNodes() {
		return nodes;
	}

	public void setNodes(List<String> nodes) {
		this.nodes = nodes;
	}

	@DynamoDBAttribute(attributeName="Materials")
	public List<String> getMaterials() {
		return materials;
	}

	public void setMaterials(List<String> materials) {
		this.materials = materials;
	}

	@DynamoDBAttribute(attributeName="RelatedCourseId")
	public String getLec_course_id() {
		return lec_course_id;
	}

	public void setLec_course_id(String lec_course_id) {
		this.lec_course_id = lec_course_id;
	}
	
	
}
