package com.csye6225.fall.Student_Info_System.datamodel;

import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
@DynamoDBTable(tableName="Lecture")
public class Lecture {
	private String Id;
	private String lectureName;
	private String lectureId;
	private List<String> nodes;
	private List<String> materials;
	private String lecture_course_id;//assume one lecture only relate to one course
	
	public Lecture() {
		this.nodes=new ArrayList<>();
		this.materials=new ArrayList<>();
	}
	

	public Lecture(String lec_Name, String lec_Id, List<String> nodes, List<String> materials, String lec_course_id) {
		super();
		this.lectureName = lec_Name;
		this.lectureId = lec_Id;
		this.nodes = nodes;
		this.materials = materials;
		this.lecture_course_id = lec_course_id;
	}

	
	@DynamoDBHashKey(attributeName="Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return Id;
	}


	public void setId(String id) {
		Id = id;
	}

	@DynamoDBAttribute(attributeName="nodes")
	public List<String> getNodes() {
		return nodes;
	}

	public void setNodes(List<String> nodes) {
		this.nodes = nodes;
	}

	@DynamoDBAttribute(attributeName="materials")
	public List<String> getMaterials() {
		return materials;
	}

	public void setMaterials(List<String> materials) {
		this.materials = materials;
	}

	@DynamoDBAttribute(attributeName="lectureName")
	public String getLectureName() {
		return lectureName;
	}


	public void setLectureName(String lectureName) {
		this.lectureName = lectureName;
	}


	@DynamoDBIndexHashKey(attributeName="lectureId",globalSecondaryIndexName="lectureId-index")
	public String getLectureId() {
		return lectureId;
	}


	public void setLectureId(String lectureId) {
		this.lectureId = lectureId;
	}


	@DynamoDBAttribute(attributeName="relatedCourses")
	public String getLecture_course_id() {
		return lecture_course_id;
	}


	public void setLecture_course_id(String lecture_course_id) {
		this.lecture_course_id = lecture_course_id;
	}

	
	
}
