package com.csye6225.fall.Student_Info_System.datamodel;

import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
@DynamoDBTable(tableName="Program")
public class Program {
	private String Id;
	private String programName;
	private String programId;
	private List<String> coursesOfProgram;
	private List<Student> enrolledStudent;
	private List<Professor> hasProfessors;
	
	public Program() {
		this.coursesOfProgram=new ArrayList<>();
		this.enrolledStudent=new ArrayList<>();
		this.hasProfessors=new ArrayList<>();
	}
	
	public Program(String programId,String programName) {
		this();
		this.programId=programId;
		this.programName=programName;
	}

	@DynamoDBHashKey(attributeName="Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return Id;
	}

	public void setId(String id) {
		Id = id;
	}

	@DynamoDBAttribute(attributeName="programName")
	public String getProgramName() {
		return programName;
	}

	public void setProgramName(String programName) {
		this.programName = programName;
	}

	@DynamoDBIndexHashKey(attributeName="programId",globalSecondaryIndexName="programId-index")
	public String getProgramId() {
		return programId;
	}

	public void setProgramId(String programId) {
		this.programId = programId;
	}

	@DynamoDBAttribute(attributeName="coursesOfProgram")
	public List<String> getCoursesOfProgram() {
		return coursesOfProgram;
	}

	public void setCoursesOfProgram(List<String> coursesOfProgram) {
		this.coursesOfProgram = coursesOfProgram;
	}

	@DynamoDBAttribute(attributeName="enrolledStudentsId")
	public List<Student> getEnrolledStudent() {
		return enrolledStudent;
	}

	public void setEnrolledStudent(List<Student> enrolledStuId) {
		this.enrolledStudent = enrolledStuId;
	}

	@DynamoDBAttribute(attributeName="professorID")
	public List<Professor> getHasProfessors() {
		return hasProfessors;
	}

	public void setHasProfessors(List<Professor> professorsId) {
		this.hasProfessors = professorsId;
	}
	
	
}
