package com.csye6225.fall.Student_Info_System.datamodel;

import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
@DynamoDBTable(tableName="Program")
public class Program {
	private String Id;
	private String programName;
	private String programId;
	private List<String> coursesOfProgram;
	private List<Student> enrolledStuId;
	private List<Professor> professorsId;
	
	public Program() {
		this.coursesOfProgram=new ArrayList<>();
		this.enrolledStuId=new ArrayList<>();
		this.professorsId=new ArrayList<>();
	}
	
	public Program(String programId,String programName) {
		this();
		this.programId=programId;
		this.programName=programName;
	}

	@DynamoDBHashKey(attributeName="Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return Id;
	}

	public void setId(String id) {
		Id = id;
	}

	@DynamoDBAttribute(attributeName="programName")
	public String getProgramName() {
		return programName;
	}

	public void setProgramName(String programName) {
		this.programName = programName;
	}

	@DynamoDBIndexHashKey(attributeName="programId",globalSecondaryIndexName="Program_ProgramId")
	public String getProgramId() {
		return programId;
	}

	public void setProgramId(String programId) {
		this.programId = programId;
	}

	@DynamoDBAttribute(attributeName="coursesOfProgram")
	public List<String> getCoursesOfProgram() {
		return coursesOfProgram;
	}

	public void setCoursesOfProgram(List<String> coursesOfProgram) {
		this.coursesOfProgram = coursesOfProgram;
	}

	@DynamoDBAttribute(attributeName="enrolledStudentsId")
	public List<Student> getEnrolledStuId() {
		return enrolledStuId;
	}

	public void setEnrolledStuId(List<Student> enrolledStuId) {
		this.enrolledStuId = enrolledStuId;
	}

	@DynamoDBAttribute(attributeName="professorID")
	public List<Professor> getProfessorsId() {
		return professorsId;
	}

	public void setProfessorsId(List<Professor> professorsId) {
		this.professorsId = professorsId;
	}
	
	
}
