package com.csye6225.fall.Student_Info_System.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Registrar")
public class Registrar {
	private String Id;
	private String registrationId;
	private String offeringId;
	private String offerType;//(Course,Counseling)
	private String department;
	private int perUnitPrice;//(number,in USD)
	
	public Registrar() {}

	
	
	
	
	public Registrar(String registrationId, String offeringId, String offerType, String department, int perUnitPrice) {
		super();
		this.registrationId = registrationId;
		this.offeringId = offeringId;
		this.offerType = offerType;
		this.department = department;
		this.perUnitPrice = perUnitPrice;
	}





	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName="Id")
	public String getId() {
		return Id;
	}

	public void setId(String id) {
		Id = id;
	}

	@DynamoDBAttribute(attributeName="registrationId")
	public String getRegistrationId() {
		return registrationId;
	}

	public void setRegistrationId(String registrationId) {
		registrationId = registrationId;
	}

	@DynamoDBAttribute(attributeName="offeringId")
	public String getOfferingId() {
		return offeringId;
	}

	public void setOfferingId(String offeringId) {
		offeringId = offeringId;
	}

	@DynamoDBAttribute(attributeName="offerType")
	public String getOfferType() {
		return offerType;
	}

	public void setOfferType(String offerType) {
		offerType = offerType;
	}
	
	
	@DynamoDBAttribute(attributeName="department")
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@DynamoDBAttribute(attributeName="perUnitPrice")
	public int getPerUnitPrice() {
		return perUnitPrice;
	}

	public void setPerUnitPrice(int perUnitPrice) {
		perUnitPrice = perUnitPrice;
	}
	
	
}
